# Generated by Django 5.2.7 on 2025-10-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_materno', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('ubigeo', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
    ]
